---
title: "Opportunities"
output:
  html_document:
    toc: true
    toc_float:
      smooth_scroll: true
---
```{css, echo=FALSE}
h3 {
  text-align: center;
}
```

<hr />

## Graduate positions

Our lab is located in Auburn's College of Forestry, Wildlife and Environment, which offers [M.S. and Ph.D. degrees in Wildlife Sciences](https://cfwestaging.wpenginepowered.com/graduate-study/graduate-degrees/). Graduate positions in the lab are fully funded (covering tuition and stipend), but availability is limited. Funding typically comes through two main pathways:

1. *Project-specific funding*. Most wildlife graduate positions are tied to externally funded research projects. In these cases, collaborators provide funding to support a graduate student who will lead fieldwork and conduct data analysis on an established research question. When available, these opportunities will be posted below, and on [Texas A&M's Natural Resources Job Board](https://jobs.rwfm.tamu.edu) and the [Ornithology Exchange](https://ornithologyexchange.org/jobs/board/).

2. *Student-specific funding*. Some competitive fellowships provide funding directly to students, offering greater flexibility in research topics. The most notable of these is the [NSF Graduate Research Fellowship Program](https://www.nsf.gov/funding/opportunities/grfp-nsf-graduate-research-fellowship-program). These fellowships are highly competitive, but we're happy to collaborate with prospective students on applications when our research interests align.

<br/>

### Current openings
**Ph.D. Position: Studying avian ecology using automated telemetry systems**

The Berigan lab (https://liamaberigan.github.io) at Auburn University College of Forestry, Wildlife and Environment is hiring a PhD student to study avian community and breeding ecology in collaboration with the University of Rhode Island (URI). The successful applicant will lead a project with two elements: 

1) *Local automated radiotelemetry*. The student will use data from a local automated radiotelemetry network, run by the University of Rhode Island, to study a variety of bird species using early successional habitat. The student’s dissertation will include an assessment of methodologies for modeling bird movements using these platforms and will address basic ecological questions about the effect of game species management on non-game birds.

2) *Migratory tracking of grassland birds*. The student will assist in deploying Motus transmitters on grassland birds in Alabama’s Black Belt Prairie ecoregion, with the aim of delineating migratory connectivity and examining declines in grassland bird populations.

Minimum qualifications:

- Master’s degree (awarded or anticipated) in biology or a related discipline. This requirement may be waived for exceptional candidates.
- Experience working with the programming language R
- Demonstrated interest in avian ecology
- Strong communication skills in oral and written English
- Ability to work independently and as part of an interdisciplinary team
- Self-motivation, a positive attitude, and strong interpersonal skills

Desired qualifications:

- Interest in collecting and/or analyzing avian movement data, especially using the Motus network
- Experience handling and banding birds, and particularly transmitter application
- Record of publication, or efforts towards publication in peer-reviewed journals

The successful applicant will be asked to apply to Auburn University’s College of Forestry, Wildlife and Environment for admission in Spring 2027, and will be expected to arrive prior to the first day of classes (January 6th). Note that GRE scores are not required for admission but may create opportunities for additional funding support (e.g., Auburn Presidential Graduate Opportunity Program). If you have GRE scores, please submit them as a part of your application package.

Compensation: Stipend of $28,000 per year, plus a tuition waiver. 

How to apply: Please email Dr. Liam Berigan (lib0016@auburn.edu) a single PDF document containing a 1) cover letter, 2) CV, 3) unofficial transcripts from all colleges attended, 4) GRE scores (if available), and 5) contact information for 3 professional references. Please title your email “PhD application: [your name]” to ensure it is routed correctly. Application deadline is August 31st, but I encourage you to apply early as applications will be evaluated on a rolling basis until a suitable candidate is found. More information about our graduate program can be found here: https://cfwe.auburn.edu/graduate-study/graduate-degrees/.


<br/>

<hr />

## Undergraduate opportunities

Any undergraduate students at Auburn who are interested in becoming involved in the lab are encouraged to get in touch. Involvement might include volunteering, pursuing an independent research project, or applying for an [Undergraduate Research Fellowship](https://our.auburn.edu/undergraduate-research-fellowship/). Feel free to send Dr. Berigan an [email](mailto:lib0016@auburn.edu) outlining your research interests and he'd be happy to set a meeting to talk more about potential projects that might be a good fit.

<br/>

<hr />

## Seasonal work opportunities

Our lab frequently hires seasonal technicians for large field projects, but those positions are dependent on project-specific funding. We will post those positions here as they become available.
